version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    expose:
      - 5000
    command: python _WEBDEV_PRO.py
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 5000:80
    depends_on:
      - web
